import fs from 'node:fs';
import path from 'node:path';
import { CommandError, run } from './exec.js';
import type { TmuxWindow } from '../../shared/types.js';

export interface TmuxSession {
  name: string;
  windows: number;
  attached: number;
  path: string;
}

const SEP = '\u001f';
const SESSION_FORMAT = ['#{session_name}', '#{session_windows}', '#{session_attached}', '#{session_path}'].join(SEP);
const WINDOW_FORMAT = ['#{session_name}', '#{window_index}', '#{window_name}', '#{pane_current_command}'].join(SEP);

/** Viewer sessions (one per open browser terminal) contain `~` and are hidden from listings. */
export function isViewerSession(name: string): boolean {
  return name.includes('~');
}

export function parseSessions(out: string): TmuxSession[] {
  return out
    .split('\n')
    .filter((l) => l.length > 0)
    .map((line) => {
      const [name = '', windows = '0', attached = '0', p = ''] = line.split(SEP);
      return { name, windows: Number(windows), attached: Number(attached), path: p };
    })
    .filter((s) => !isViewerSession(s.name));
}

export function parseWindows(out: string): Map<string, TmuxWindow[]> {
  const bySession = new Map<string, TmuxWindow[]>();
  for (const line of out.split('\n')) {
    if (!line) continue;
    const [session = '', index = '0', name = '', command = ''] = line.split(SEP);
    if (isViewerSession(session)) continue;
    const list = bySession.get(session) ?? [];
    list.push({ index: Number(index), name, command });
    bySession.set(session, list);
  }
  return bySession;
}

function isNoServer(err: unknown): boolean {
  return (
    err instanceof CommandError &&
    /no server running|error connecting|no sessions/i.test(err.stderr)
  );
}

export const TMUX_CONF = `# Generated by remote-ai. Applies only to the dedicated tmux server (tmux -L <socket>).
set -g mouse on
set -g history-limit 50000
set -g status off
set -sg escape-time 10
set -g focus-events on
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",xterm-256color:RGB"
set -g window-size latest
setw -g aggressive-resize on
set -g allow-rename off
setw -g automatic-rename off
`;

export class Tmux {
  readonly confPath: string;

  constructor(
    readonly socket: string,
    dataDir: string,
  ) {
    this.confPath = path.join(dataDir, 'tmux.conf');
    fs.writeFileSync(this.confPath, TMUX_CONF);
  }

  /** Arguments that select our tmux server; also used when spawning attach clients. */
  baseArgs(): string[] {
    return ['-L', this.socket, '-f', this.confPath];
  }

  exec(args: string[], input?: string): Promise<string> {
    return run('tmux', [...this.baseArgs(), ...args], { input, label: `tmux ${args[0]}` });
  }

  /** `-f` only applies when the tmux server starts, so re-apply it to a server that is already running. */
  async reloadConfig(): Promise<void> {
    try {
      await this.exec(['source-file', this.confPath]);
    } catch (err) {
      if (!isNoServer(err)) throw err;
    }
  }

  async listSessions(): Promise<TmuxSession[]> {
    try {
      return parseSessions(await this.exec(['list-sessions', '-F', SESSION_FORMAT]));
    } catch (err) {
      if (isNoServer(err)) return [];
      throw err;
    }
  }

  async listWindows(): Promise<Map<string, TmuxWindow[]>> {
    try {
      return parseWindows(await this.exec(['list-windows', '-a', '-F', WINDOW_FORMAT]));
    } catch (err) {
      if (isNoServer(err)) return new Map();
      throw err;
    }
  }

  async hasSession(name: string): Promise<boolean> {
    try {
      await this.exec(['has-session', '-t', `=${name}`]);
      return true;
    } catch {
      return false;
    }
  }

  async newSession(opts: { name: string; cwd: string; window: string; env: Record<string, string> }): Promise<void> {
    const envArgs = Object.entries(opts.env).flatMap(([k, v]) => ['-e', `${k}=${v}`]);
    await this.exec([
      'new-session', '-d', '-s', opts.name, '-n', opts.window, '-c', opts.cwd, '-x', '200', '-y', '50', ...envArgs,
    ]);
  }

  async newWindow(session: string, window: string, cwd: string): Promise<void> {
    await this.exec(['new-window', '-d', '-t', `=${session}:`, '-n', window, '-c', cwd]);
  }

  async killSession(name: string): Promise<void> {
    await this.exec(['kill-session', '-t', `=${name}`]);
  }

  /** Type text literally, as if pasted character by character. */
  async sendText(target: string, text: string): Promise<void> {
    await this.exec(['send-keys', '-t', target, '-l', text]);
  }

  /** Send tmux key names such as Enter, Escape, C-c, BTab, Up. */
  async sendKeys(target: string, keys: string[]): Promise<void> {
    await this.exec(['send-keys', '-t', target, ...keys]);
  }

  /** Paste text using bracketed paste so multi-line input arrives as one paste. */
  async paste(target: string, text: string): Promise<void> {
    const buffer = `ra-${process.pid}-${Date.now()}`;
    await this.exec(['load-buffer', '-b', buffer, '-'], text);
    await this.exec(['paste-buffer', '-p', '-d', '-b', buffer, '-t', target]);
  }

  /** The visible screen of a pane as plain text. */
  async capture(target: string): Promise<string> {
    return this.exec(['capture-pane', '-p', '-t', target]);
  }
}
